png(file = "plot4.png")
power <- read.table("household_power_consumption.txt", sep=";", header=TRUE, stringsAsFactors = FALSE)
power$Date <- dmy(power$Date)
powersub <- subset(power, power$Date == "2007-02-01" | power$Date == "2007-02-02")
powersub$Global_active_power <- as.numeric(powersub$Global_active_power)
powersub$Voltage = as.numeric(powersub$Voltage)
powersub$Global_reactive_power = as.numeric(powersub$Global_reactive_power)
powersub$Sub_metering_2 = as.numeric(powersub$Sub_metering_2)
powersub$Sub_metering_1 = as.numeric(powersub$Sub_metering_1)
par(mfrow = c(2,2))
plot(strptime(paste(powersub$Date, powersub$Time), "%Y-%m-%d %H:%M:%S"), powersub$Global_active_power, type="l", xlab="", ylab="Global Active Power (kilowatts)")
plot(strptime(paste(powersub$Date, powersub$Time), "%Y-%m-%d %H:%M:%S"), powersub$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(strptime(paste(powersub$Date, powersub$Time), "%Y-%m-%d %H:%M:%S"), powersub$Sub_metering_1, type="l", xlab="", ylab="Energy Sub Metering")
lines(strptime(paste(powersub$Date, powersub$Time), "%Y-%m-%d %H:%M:%S"), powersub$Sub_metering_2, type="o", col = "red")
lines(strptime(paste(powersub$Date, powersub$Time), "%Y-%m-%d %H:%M:%S"), powersub$Sub_metering_3, type="o", col = "blue")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lty=1)
plot(strptime(paste(powersub$Date, powersub$Time), "%Y-%m-%d %H:%M:%S"), powersub$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()