png(file = "plot3.png")
power <- read.table("household_power_consumption.txt", sep=";", header=TRUE, stringsAsFactors = FALSE)
power$Date <- dmy(power$Date)
powersub <- subset(power, power$Date == "2007-02-01" | power$Date == "2007-02-02")
powersub$Global_active_power <- as.numeric(powersub$Global_active_power)
powersub$Voltage = as.numeric(powersub$Voltage)
powersub$Global_reactive_power = as.numeric(powersub$Global_reactive_power)
powersub$Sub_metering_2 = as.numeric(powersub$Sub_metering_2)
powersub$Sub_metering_1 = as.numeric(powersub$Sub_metering_1)
plot(strptime(paste(powersub$Date, powersub$Time), "%Y-%m-%d %H:%M:%S"), powersub$Sub_metering_1, type="l", xlab="", ylab="Energy Sub Metering")
lines(strptime(paste(powersub$Date, powersub$Time), "%Y-%m-%d %H:%M:%S"), powersub$Sub_metering_2, type="o", col = "red")
lines(strptime(paste(powersub$Date, powersub$Time), "%Y-%m-%d %H:%M:%S"), powersub$Sub_metering_3, type="o", col = "blue")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lty=1)
dev.off()
